# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'uKeeper' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Charts'
  pod 'CocoaLumberjack'
  pod 'EasyToast'
  # Pods for MbedRSDemo

  target 'uKeeperTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'uKeeperUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
